"""add zipcode

Revision ID: c4cc12988caa
Revises: b8ad78dec6da
Create Date: 2025-12-20 21:10:37.061004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4cc12988caa'
down_revision: Union[str, Sequence[str], None] = 'b8ad78dec6da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('zipcode', sa.String(length=150), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'zipcode')
    # ### end Alembic commands ###
